name: Run PHPUnit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, pdo_mysql

    - name: Install dependencies
      working-directory: ./api
      run: composer install --no-progress --prefer-dist

    - name: Run tests
      working-directory: ./api
      run: bin/phpunit
